#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ErgoMobile.Resource", IsApplication=true)]

namespace ErgoMobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ba = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bn = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bns = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bs = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bselected = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bshape = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000b
			public const int Aplicacao = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int NomeInspecao = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int Responsavel = 2131034122;
			
			// aapt resource value: 0x7f050018
			public const int ajuda = 2131034136;
			
			// aapt resource value: 0x7f05001c
			public const int app1 = 2131034140;
			
			// aapt resource value: 0x7f050023
			public const int atrbnota = 2131034147;
			
			// aapt resource value: 0x7f050028
			public const int btnBom = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int btnMtoBom = 2131034153;
			
			// aapt resource value: 0x7f050025
			public const int btnMtoRuim = 2131034149;
			
			// aapt resource value: 0x7f050027
			public const int btnRegular = 2131034151;
			
			// aapt resource value: 0x7f050026
			public const int btnRuim = 2131034150;
			
			// aapt resource value: 0x7f050004
			public const int button2 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int button3 = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int button4 = 2131034119;
			
			// aapt resource value: 0x7f05001f
			public const int cadastrar = 2131034143;
			
			// aapt resource value: 0x7f050015
			public const int en = 2131034133;
			
			// aapt resource value: 0x7f05001e
			public const int func1 = 2131034142;
			
			// aapt resource value: 0x7f050017
			public const int inspecoes = 2131034135;
			
			// aapt resource value: 0x7f050021
			public const int item = 2131034145;
			
			// aapt resource value: 0x7f050011
			public const int lado1 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int lado2 = 2131034130;
			
			// aapt resource value: 0x7f050001
			public const int linearLayout1 = 2131034113;
			
			// aapt resource value: 0x7f050013
			public const int linearLayout2 = 2131034131;
			
			// aapt resource value: 0x7f05002a
			public const int linearLayout3 = 2131034154;
			
			// aapt resource value: 0x7f05000e
			public const int list1 = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int list2 = 2131034128;
			
			// aapt resource value: 0x7f050020
			public const int menucheck = 2131034144;
			
			// aapt resource value: 0x7f05001a
			public const int name = 2131034138;
			
			// aapt resource value: 0x7f050016
			public const int novains = 2131034134;
			
			// aapt resource value: 0x7f050024
			public const int pergunta = 2131034148;
			
			// aapt resource value: 0x7f05002e
			public const int plotView1 = 2131034158;
			
			// aapt resource value: 0x7f05002c
			public const int proximo = 2131034156;
			
			// aapt resource value: 0x7f050014
			public const int pt = 2131034132;
			
			// aapt resource value: 0x7f05000d
			public const int resultados = 2131034125;
			
			// aapt resource value: 0x7f050000
			public const int space1 = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int space2 = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int space3 = 2131034118;
			
			// aapt resource value: 0x7f050022
			public const int space4 = 2131034146;
			
			// aapt resource value: 0x7f05001b
			public const int textApp = 2131034139;
			
			// aapt resource value: 0x7f05001d
			public const int textFuncionalidade = 2131034141;
			
			// aapt resource value: 0x7f050019
			public const int textNome = 2131034137;
			
			// aapt resource value: 0x7f050003
			public const int textView1 = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int toolbar1 = 2131034114;
			
			// aapt resource value: 0x7f05002b
			public const int voltar = 2131034155;
			
			// aapt resource value: 0x7f05002d
			public const int voltarchecklist = 2131034157;
			
			// aapt resource value: 0x7f05000f
			public const int voltarmenu = 2131034127;
			
			// aapt resource value: 0x7f05000c
			public const int voltarr = 2131034124;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Checklist = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int InspecaoLista_Layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int lista2 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int listainspecao = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ListStyle = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ListStyle2 = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int NovaInspecao = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Questionario = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ResultScreen = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
